### PR TITLE
Jsonpatch

### PR DESCRIPTION
**Pull request by KevinDockx**
Rename SimpleObjectAdapter to ObjectAdapter to stay in line with upcoming changes (for dynamic support)

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@KevinDockx__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft Open Technologies, Inc. and real humans are currently evaluating your PR.</p>

TTYL, MSOTBOT;

**Comment by KevinDockx** [comment]
Latest commit auto-added: statuscode is now included in JsonPatchException

**Comment by kirthik** [comment]
:shipit:

**Comment by kirthik** [comment]
Since we are branching today afternoon for beta4 release, I checked this in - 0462dd6be39c031e04495e1fd22c4b0f9b30ba1f

**Pull request closed without merging**
