### PR TITLE
Do not serve response body for HEAD requests

### PR DESCRIPTION
**Pull request by jbagga**
Addresses #7208

### CODE REVIEW

**Comment by jbagga** [comment]
No these don't. There are unit tests that check that for GET. I can add Content-Length to these tests for HEAD

**Comment by jbagga** [comment]
@Tratcher https://github.com/aspnet/Mvc/issues/6875 We only set Content-Length when serving the body? Should HEAD be special cased and set Content-Length?

**Comment by jbagga** [comment]
Actually we can set it for all requests that get to that line since we short-circuit return for 304 and 412 before we even get to setting Content-Length. I will remove the check if(serveBody) before we set Content-Length here https://github.com/aspnet/Mvc/blame/dev/src/Microsoft.AspNetCore.Mvc.Core/Infrastructure/FileResultExecutorBase.cs#L89

**Comment by jbagga** [comment]
@Tratcher Updated

**Comment by dustinmoris** [comment]
In order to avoid any mistakes for HEAD requests I think the safest would be to remove all HEAD checks from the code and place only a single if statement at the very end of the execution just above the line where you'd start writing to the body of the response:
```
if !(isHeadRequest) then
 {
    StreamCopyOperation.CopyToAsync(..)
//..
}

In this case you make sure that the HEAD request will be exactly equivalent to a GET request except it won't ever include a response body.

**Pull request merged**
