### PR TITLE
Update MvcCoreServiceCollectionExtensions.cs

### PR DESCRIPTION
**Pull request by danroth27**

### CODE REVIEW

**Comment by Eilon** [comment]
What's the bug?

**Comment by rynowak** [comment]
I have a guess but I want to hear it from dan...

**Comment by danroth27** [comment]
When you request a service from the built service provider it will give you the last service added, not the first one. This method should mimic the DI behavior. 

This issue doesn't generally affect user scenarios today, because this method is used to extract the hosting environment service and there is typically only one of those. I hit this issue as part of my module prototyping when I added a new hosting environment for each module. The added hosting environment should override the existing one, but currently it doesn't because this method picks the first instead of the last. I'm working around this right now by simply removing the app hosting environment for each module.

**Comment by dougbu** [comment]
But @danroth27, @danroth27, @danroth27  how an triage handle this issue if you haven't filed an [issue](https://github.com/aspnet/Mvc/issues/new)?

**Comment by Eilon** [comment]
Logged https://github.com/aspnet/Mvc/issues/5554.

@dougbu can you figure out how to add a unit test for this as well?

**Comment by dougbu** [comment]
@danroth27 this looks ready to :shipit:  But I'll wait 'til I have an approved PR that adds the appropriate test. Will get the two in at the same time.

**Comment by dougbu** [comment]
48546db

**Comment by dougbu** [comment]
Corrected commit ref

**Pull request closed without merging**
