### PR TITLE
Remove T4 custom tool

### PR DESCRIPTION
**Pull request by dougbu**
- use same generator as most other projects in aspnet repos
- were not using named arguments to resource methods anyhow

### CODE REVIEW

**Comment by dougbu** [comment]
FYI mostly

**Comment by dougbu** [comment]
@natemcmaster @pranavkm @ryanbrandenburg a quick confirmation: We don't plan to remove the `resx` target (and use regular generator) i.e. I'm not migrating toward something that's about to go.

**Comment by natemcmaster** [comment]
Actually, we do plan to remove the resx target. I can't promise a timeline on it, but removing our custom resx targets is part of the plan to converge with Arcade. See The MicroBuild team won't let us use MicroBuild.Plugins.Signing in TeamCity agents, so this basically copies the API

**Comment by natemcmaster** [comment]
Oops, copy paste fail. See https://github.com/aspnet/BuildTools/issues/728

**Comment by dougbu** [comment]
@natemcmaster is aspnet/BuildTools#728 likely to make it in 2.2?

**Comment by natemcmaster** [comment]
No.

**Comment by natemcmaster** [comment]
Attempting to trigger VSTS validations.

**Pull request merged**
