### PR TITLE
Another `System.RuntimeSerialization.Xml` version update

### PR DESCRIPTION
**Pull request by dougbu**
- see also d4163b4

nit: sort properties

### CODE REVIEW

**Comment by dougbu** [comment]
@rynowak should this also be merged into the `release` branch?

**Comment by dougbu** [comment]
This PR fixes #3493 on the `release` branch.

**Comment by dougbu** [comment]
:up::date: (rebased)

**Comment by rynowak** [comment]
:shipit:  - I think this is going to have to go into release. Paging @Eilon

**Comment by dougbu** [comment]
cef4a66

**Pull request merged**
