### PR TITLE
Added `ViewResultTest`s.

### PR DESCRIPTION
**Pull request by Haplois**
Fixed https://github.com/aspnet/Mvc/issues/4906.

Initial check-in.

### CODE REVIEW

**Comment by pranavkm** [comment]
Aren't there tests here - https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNetCore.Mvc.ViewFeatures.Test/ViewResultTest.cs?

**Comment by javiercn** [comment]
:shipit:

**Comment by javiercn** [comment]
@Eilon Am I good to merge this one?

**Comment by Eilon** [comment]
@javiercn yup.

**Pull request merged**
