### PR TITLE
Fix ActionMethodExecutor incorrectly setting DeclaredType on ObjectRe…

### LINKED ISSUE #7782: XmlSerializerOutputFormatter throws InvalidCastException on async method
#### Is this a Bug or Feature request?:
Bug, regression

#### Steps to reproduce or link to a repro project:
- Create an Asp.Net Core api project
- Update package to use 2.1.0-rc1-final
``` xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.0-rc1-final" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.4" />
  </ItemGroup>

</Project>
```
- Add XmlSerializerOutputFormatter in MVC option
``` csharp
public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc(options =>
            {
                options.OutputFormatters.Add(new XmlSerializerOutputFormatter());
            });
        }
```
- Update a ValuesController method to use async 
``` csharp
 public async Task<IEnumerable<string>> Get()
        {
            return await Task.FromResult(new string[] { "value1", "value2" });
        }
```
- run the project
- send a request using Accept: application/xml
``` 
GET /api/values HTTP/1.1
Host: localhost:61519
Accept: application/xml
```

#### Description of the problem:
An `InvalidCastException` is thrown  

> InvalidCastException: Unable to cast object of type &#x27;System.String[]&#x27; to type &#x27;System.Threading.Tasks.Task`1[System.Collections.Generic.IEnumerable`1[System.String]]&#x27;.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:
Microsoft.AspNetCore.All Version="2.1.0-rc1-final"

### PR DESCRIPTION
**Pull request by pranavkm**
…sult

Fixes #7782

### CODE REVIEW

**Comment by pranavkm** [comment]
FYI @mkArtakMSFT \ @kichalla

**Comment by pranavkm** [comment]
@natemcmaster - anything more I need to do here?

**Comment by natemcmaster** [comment]
>  anything more I need to do here?

Not in terms of infrastructure. Just get sign off from people who actually know what's going on in this change.

**Comment by pranavkm** [comment]
👍

**Pull request merged**
