### PR TITLE
Only go async when flush async

### PR DESCRIPTION
**Pull request by benaadams**
@dougbu I saw this in your traces from  #5320 but can't seem to get the async paths to trigger to measure the difference

What tests were you running? The `.ps1` ones?

### CODE REVIEW

**Comment by benaadams** [comment]
Ahh... debug...

**Comment by dougbu** [comment]
FYI @benaadams later images in #5320 use Release bits.

**Comment by dougbu** [comment]
Does this PR actually reduce allocations in any current Performance scenario when using Release bits?

**Comment by benaadams** [comment]
No, which is why I was confused 😁

**Comment by dougbu** [comment]
> What tests were you running? The .ps1 ones?

Generally yes. For the BasicViews scenario, I use `.\loadtest.ps1 -rps 20 -variation htmlhelpers` b/c the default 100 RPS leads to more noise in the profile and the other scenarios I've been using also focus on HTML helpers. (My changes in #5320 should result in similar reductions but less percentage-wise since tag helper scenarios use more memory.)

**Comment by dougbu** [comment]
> No, which is why I was confused 😁 

So should we close this PR?

**Pull request closed without merging**
