### PR TITLE
Reacting to NullLoggerFactory removal

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by NTaylorMullen** [comment]
:shipit:

**Comment by dougbu** [comment]
is this change still needed?  could we instead use the new `NullLoggerFactory` in the Common repo?

**Comment by dougbu** [comment]
:watch:

**Comment by NTaylorMullen** [comment]
No reason for the NullLoggerFactory in common repo anymore, it's moving to testing. `NullLoggerFactory` is equivalent to `new LoggerFactory()`

**Pull request closed without merging**
