### PR TITLE
doc: Add link to comunity device detector package

### PR DESCRIPTION
**Pull request by laskoviymishka**
see #4877 to more details.

cc @Eilon

### CODE REVIEW

**Comment by laskoviymishka** [comment]
@shotor not really sure which exact title should i change.

**Comment by Eilon** [comment]
I added an `s` to the word `application` for better grammar. Thanks for the PR!

**Comment by laskoviymishka** [comment]
@Eilon  sorry for bad grammar  😭

**Comment by Eilon** [comment]
Haha no worries! 😄

**Pull request merged**
