### PR TITLE
Fixing minor error with comment

### PR DESCRIPTION
**Pull request by stevejgordon**
A very minor contribution to fix a slight error with one of the comments I noticed while looking at a recent commit.

### CODE REVIEW

**Comment by kichalla** [comment]
:shipit:

**Comment by Eilon** [comment]
@ryanbrandenburg please have a quick look and merge.

**Comment by ryanbrandenburg** [comment]
Yep, that's a :shipit:, I'll merge it.

**Comment by ryanbrandenburg** [comment]
Merged. Thanks for the fix @stevejgordon!

**Pull request closed without merging**
