### PR TITLE
React to ICompileModule change in DNX

### PR DESCRIPTION
**Pull request by troydai**
https://github.com/aspnet/dnx/pull/1678

Won't merge until the PR on DNX is finished.

### CODE REVIEW

**Comment by pranavkm** [comment]
:shipit:

**Comment by dougbu** [comment]
:shipit: once `build.cmd` runs cleanly

**Comment by troydai** [comment]
@pranavkm @dougbu @davidfowl 

Change in DNX has been merged to: https://github.com/aspnet/dnx/commit/46fa4afc233c01ea7192beb0c182c5ea41c28cff

This PR is updated.

**Comment by troydai** [comment]
Build pass locally (with `build verify`). As soon as a new DNX build is finished on CI, the MVC build will be broken by any minute. I'll merge this change soon.

**Pull request merged**
