### PR TITLE
Renamed PhysicalFileProviderResult to PhysicalFileResult

### PR DESCRIPTION
**Pull request by kichalla**
@pranavkm

### CODE REVIEW

**Comment by pranavkm** [comment]
Do we need to change `VirtualFileProviderResult`?

**Comment by kichalla** [comment]
good point...i updated the PR to include this name change too...

**Comment by pranavkm** [comment]
:shipit:

**Comment by Eilon** [comment]
:shipit: but FYI your branch looks messed up (it has your session state changes in it).

**Comment by kichalla** [comment]
eef6c3883a7e27b8387b0925f0b6a88df0a484c5

**Comment by Shazwazza** [comment]
would be great to put this on the announcements board as a breaking change

**Comment by Eilon** [comment]
@Shazwazza the result types aren't used very frequently because most people use the factory methods on `Controller`. We want to avoid "too many" announcements so that most people will continue to find it useful.

**Comment by Shazwazza** [comment]
Fair enough, I found this so no worries ;)

**Pull request closed without merging**
