### PR TITLE
Change inject directive to format correctly after newline during design time.

### PR DESCRIPTION
**Pull request by NTaylorMullen**
- Also modified existing tests to account for aspnet/Razor#332 which fixed models formatting after newline.
- Updated tests for inject to understand new formatting parsing.

aspnet/Razor#332

**Razor PR:** https://github.com/aspnet/Razor/pull/360

### CODE REVIEW

**Comment by pranavkm** [comment]
:shipit:

**Comment by dougbu** [comment]
is `@model` already limited to a single line?  if not, why not isn't it changing in this PR?

**Comment by dougbu** [comment]
:watch:

**Comment by NTaylorMullen** [comment]
@dougbu `@model` uses the same core parsing mechanics as `@inherits` which is covered in the Razor PR. I updated the `@model` tests in this PR.

**Comment by dougbu** [comment]
> which is covered in the Razor PR

excellent.  pls update commit description here to mention aspnet/Razor#360 (better, the final Razor commit when you push) also handled `@model`

:shipit: from me

**Pull request merged**
