### PR TITLE
Removed unnecessary dependency in UrlHelper

### PR DESCRIPTION
**Pull request by ivaylokenov**
IActionSelector is injected in UrlHelper but it is not used. Edited all tests where a mock of IActionSelector was used to instantiate UrlHelper and all of them pass.

### CODE REVIEW

**Comment by rynowak** [comment]
This is another great cleanup. Thanks!

**Comment by ivaylokenov** [comment]
You are welcome! :+1:

**Comment by rynowak** [comment]
:shipit: - I'll merge this shortly.

**Comment by rynowak** [comment]
For future changes, please try to rebase onto `dev` before submitting. I had to cherry-pick the last commit of this because you had a merge in your history.

**Comment by rynowak** [comment]
1c34d88f4c21998cdd7c902563437c87db0c3b75

**Comment by ivaylokenov** [comment]
OK, @rynowak , I am sorry. Lesson learned. Thanks!

**Pull request closed without merging**
