### PR TITLE
DefaultAssemblyPartDiscoveryProvider.IsCandidateLibrary should not look at types i…

### LINKED ISSUE #4363: DefaultAssemblyProvider.IsCandidateLibrary should not look at types in Mvc assemblies
We used to have code in the DNX based assembly provider where you'd skip any assembly in the `ReferenceAssemblies` list as not a candidate (https://github.com/aspnet/Mvc/commit/991dff6b9ee781d3525838f799e2965aa9d9cfb4#diff-332c12c286fe3090208e27923a147e2cL86). This seems to have been lost in transition to DependencyModel. We should bring that back.

### PR DESCRIPTION
**Pull request by pranavkm**
…n Mvc assemblies

Fixes #4363

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @javiercn \ @rynowak

**Comment by javiercn** [comment]
This will affect AddTagHelpersAsServices as we need to discover the ones we provide out of the box.

**Comment by javiercn** [comment]
Also, I'm working on dramatic change to this class, we might want to wait and do it later

**Comment by pranavkm** [comment]
@javiercn, what's the PR for your change?

**Comment by javiercn** [comment]
https://github.com/aspnet/Mvc/pull/4379

**Comment by javiercn** [comment]
You can rebase this PR on top of my changes :)

**Comment by pranavkm** [comment]
:up: :date:

**Comment by javiercn** [comment]
Is there anything that we provide out of the box apart from tag helpers? (I'm pretty sure we don't, but want to make sure). If there's something else that we provide out of the box, you need to add it to the list of default parts. If not, :shipit:

**Comment by pranavkm** [comment]
Sorry, I don't understand what out of the box means here.

**Comment by javiercn** [comment]
As part of the framework, like input tag helper and similar, I don't think we provide any view component or a controller, but just wanted to make you aware. :shipit:

**Pull request closed without merging**
