### PR TITLE
Fast-path PrefixEnumerator

### PR DESCRIPTION
**Pull request by benaadams**
Use reference test, also only test for equality if exact prefix match found

/cc @rynowak

### CODE REVIEW

**Comment by benaadams** [comment]
Looking at your hot functions in #4066 second one is MoveNext

**Comment by rynowak** [comment]
Did you measure this change? What's the impact?

This one seems a little less clear-cut since it makes the code more complicated, the struct bigger, and all of this is going to be rewritten anyway.

**Comment by rynowak** [comment]
Self assigning to track

**Comment by benaadams** [comment]
@rynowak I'm having build issues with grumpy feeds, was hoping aspnetcidev would be happy soon. Should I move to volatile?

**Comment by rynowak** [comment]
volatile should be fine for now - I checked in a bunch of **massive** improvements this morning, so things should be much better.

**Comment by benaadams** [comment]
Might need a couple runs with the profiler, but pre and post calls

pre-calls

post-calls

**Comment by benaadams** [comment]
Think it can be better and simpler

**Comment by benaadams** [comment]
post-post

@rynowak Is better now?

**Comment by rynowak** [comment]
Yeah it does look better. Seems worth taking for now... just FYI I am going to rewrite this whole class if I have time this week.

**Comment by benaadams** [comment]
Yar, is still a big player on that binding test

**Comment by rynowak** [comment]
a33369acd8b072fa41ac8f6255414e70ddf70418

**Pull request closed without merging**
