### PR TITLE
Discussion: device detection mechanism 

### LINKED ISSUE #4877: Discussion: device detection mechanism
I was unable to found any built-in mechanism that allow developer to build adaptive web site (css media queries not count).
It would be really nice to have some mechanism that allow me as a developer to introduce some mobile or tablet specific layout, views and behaiviors.  For some developers this feature is critical.

Adaptive web site should adjust his behaivior according to current device. Adaptive site should also have preference mechanism, with ability to switch between preferences, not matter for device (like github for example).
This could help a lot of developers to build rich and adaptive websites.

I propose to add such mechanism as separate nuget package with `Mvc` bundle. 

API could be something like this:
Firstly we need to include `Mvc.Mobile` or simillar package.
Than we should register required service and specify some options:
You could just add device detector:

```
services.AddDeviceDetector();
```

After this configuration new ViewLocationExpanders will be applied and start to search device specific views from prefixes or subfolders. Device would be detected from user agent according to lite device detection mechanism (simillar to _http://projects.spring.io/spring-mobile/_).

You could also add preference switcher mechanism, to enable switch:

```
services.AddDeviceSwitcher<UrlSwitcher>(switcherOptions => { }, deviceOptions => { });
```

If you specify device switcher, you should also map this switcher to some route:

```
route.MapDeviceSwitcher();
```

After that, you will have an ability to override default agent detetection with some preference, by calling URL in format: `/choose/{device}`.
Mechanism should provide following extensibility point:
1. Allow developer to change device codes, and aliases
2. Allow developer to use own device implementation, by adding specific device factory
3. Allow developer to introduce new device types expect regular table and mobile
4. Allow developer to switch between Switcher mechanism (by default, it should store preference in cookies, but also should be have ability to use URL switcher)
5. Allow developer to change URL generation rules

Implementation for such mechanism would not require a lot of effort, and not break anything (since it  could placed completely separate). 

Any thought on this one?

### PR DESCRIPTION
**Pull request by laskoviymishka**
Fixes #4877.

This PR introduced device detection, and preference switcher mechanisms. Introduced as new project, that not included in main Mvc package, so it will not break anything.

There is sample usage placed in `samples/MvcSandbox`. 
Algorithm pretty similar to _http://projects.spring.io/spring-mobile/_

This feature is really important for building adaptive web site, so it will be great to have some built-in package for this one. I not really sure where i should place this code, maybe it better to placed somewhere different. If so please advise. But it really require to have something for mobile devices detection built-in aspnet.

### CODE REVIEW

**Comment by tysonnero** [comment]
@laskoviymishka  Any progress with device detection?

**Comment by laskoviymishka** [comment]
@tysonnero this PR contains everything that need to device detection, you could checkout here _https://github.com/laskoviymishka/Mvc/tree/feat/deviceDetect_
I still waiting for any response from `aspnet` team about acceptence of this feature.

**Comment by laskoviymishka** [comment]
I publish code from this PR as separate nuget package.
You may try it as it says here _https://github.com/laskoviymishka/MvcDeviceDetector_

**Comment by Eilon** [comment]
Closing for the reasons mentioned in https://github.com/aspnet/Mvc/issues/4877#issuecomment-267169217.

**Pull request closed without merging**
