### PR TITLE
Porting HttpUnauthorizedResult from MVC5

### PR DESCRIPTION
**Pull request by ianhong**
@rynowak 

Could you please take a look at this before you leave??

Thanks,

### CODE REVIEW

**Comment by Eilon** [comment]
:shipit:

**Comment by rynowak** [comment]
:shipit:

**Comment by rynowak** [comment]
@ianhong is this merged?

**Comment by ianhong** [comment]
1144ba72d50c00d0588bf26f2c4ec63b74733aeb
Sorry. I'm closing this.

**Pull request closed without merging**
