### PR TITLE
Use `string.IsNullOrEmpty()` instead of empty string check.

### PR DESCRIPTION
**Pull request by henkmollema**
Noticed this in #2421.

### CODE REVIEW

**Comment by henkmollema** [comment]
@pranavkm @Eilon

**Comment by pranavkm** [comment]
:shipit:  cc @kichalla

**Comment by Eilon** [comment]
@kichalla can you merge?

**Comment by henkmollema** [comment]
Rebased with dev.

**Comment by kichalla** [comment]
Thanks @henkmollema ...I will merge this PR today.

**Pull request merged**
