### PR TITLE
Get builds working better within VS (temporary fix?); disable pre-compilation

### PR DESCRIPTION
**Pull request by dougbu**
- remove `RazorPreCompilation.cs` files from all but the PrecompilationWebSite
- related to #2498 but not addressing that issue since pre-compilation is what that site is about

### CODE REVIEW

**Comment by dougbu** [comment]
@Eilon @rynowak @pranavkm any thoughts on doing this until and unless we get pre-compilation working reliably when building functional tests within VS?

**Comment by rynowak** [comment]
I'd want to have @eilon 's ok, but to me anything that's blocking developer workflow needs to be addressed.

Are you seeing any issues other than errors in VS?

**Comment by dougbu** [comment]
No other issues.  In fact VS freezes more often when I'm editing in the Razor repo :frowning: 

Note this leaves the #2498 errors in play.  I could remove those 10 as well.  But then we might as well throw away the PrecompilationWebSite entirely.

**Comment by Eilon** [comment]
1. Is this a tooling bug? Runtime bug? Where is the underlying bug logged?
2. I'm ok checking this in, but also log a bug to restore these (including pointing to the changeset that removes these)

**Comment by dougbu** [comment]
@Eilon 
1. I looked at #2498 some without narrowing the problem down much.  The symptoms certainly point toward a component used only when pulling the PrecompilationWebSite into a larger VS build (but I can't think of a component unique to that scenario) or some lack of generality in the site itself, the functional test setup, VS, or the runtime. So, yeah, it's one of the bits you listed :smile: and right now #2498 is filed in MVC.
2. Sure.  Will file after I push.

In the meantime I'll add the additional errors seen without this change to the commit description.  That is, I'll make sure the change still makes a difference a few days later.

**Comment by Eilon** [comment]
@dougbu ok thanks go ahead and merge.

**Comment by rynowak** [comment]
@dougbu should this be closed?

**Comment by dougbu** [comment]
@rynowak I didn't get back to this over the last couple of days.  The change definitely makes debugging Razor code-generation orders of magnitude easier.  I'll try to reproduce the original issue(s) over the weekend and re-confirm the change helps even when not doing low-level debugging.

Will take a more definitive action in the next day or two...

**Comment by dougbu** [comment]
Checked VS behaviour without this change.  Much uglier -- 26 errors instead of the 10 (mentioned in #2498) just for PrecompilationWebSite.  And I can't start the tag helper sample from VS.

So I'll check this change in shortly.

**Comment by dougbu** [comment]
3fbead0

**Comment by dougbu** [comment]
@Eilon w.r.t.
> also log a bug to restore these (including pointing to the changeset that removes these)

I added a link to the commit in the existing #2498 which is generally about Razor precompilation issues.

**Pull request closed without merging**
