### PR TITLE
[NO MERGE] Enable dispatching in all function tests

### PR DESCRIPTION
**Pull request by JamesNK**
A branch and build to test dispatching in all functional tests.

We don't want to enable dispatching in every functional website so broken tests related to dispatching should be replicated in the RoutingWebsite and fixed there.

### CODE REVIEW

**Comment by kichalla** [comment]
@JamesNK Just FYI...I rebased this PR branch on latest commits and also fixed MvcSandbox to run on Dispatcher (as it has functional tests too)

**Comment by kichalla** [comment]
@JamesNK FYI...I updated this branch with routing branding changes

**Comment by pranavkm** [comment]
@JamesNK is this still needed?

**Comment by JamesNK** [comment]
Yes it is still useful to have around.

**Comment by JamesNK** [comment]
Similar change is already commited.

**Pull request closed without merging**
