### PR TITLE
Added Permanent property to configure redirect in RequireHttpsAttribute

### LINKED ISSUE #4561: RequireHttps - should it be redirect 302 by default?
RequireHttps uses a 301 permanent redirect.

https://github.com/aspnet/Mvc/blob/ee2cfa1963ee7f8195130d41330f94d4622ca89a/src/Microsoft.AspNetCore.Mvc.Core/RequireHttpsAttribute.cs#L87

It used to be 302 in MVC 5 AFAIK so this adds to the confusion.
All the major browsers cache 301 indefinitely so if you use RequireHttps in your code you can never remove it.
Otherwise you will have code that may not match the behaviour of your site depending on the state of the users browser cache.  This can cause some confusion without an in depth knowledge of browser behaviour and 301 vs. 302.

I realise I could override the attribute to say something like RequireHttpsNotPermanent but given the one way street that is 301 I propose making RequireHttps 302 (like it used to be) by default.  Make 301 an opt in so you are aware of the consequences.

Perhaps with an overridden RequireHttpsPermanent or RequireHttps("Permanent") attribute for 301.

Discussed at length here
https://github.com/aspnet/Security/issues/798

### PR DESCRIPTION
**Pull request by khellang**
As promised in #4579

Fixes #4561

### CODE REVIEW

**Comment by Eilon** [comment]
@khellang thanks for the PR! I've assigned this to an engineer on the team and we'll get it reviewed and merged ASAP.

**Comment by sebastienros** [comment]
LGTM, I am still trying to run it locally, facing some unrelated issues right now.

**Comment by ShadowDancer** [comment]
That's great, but how can I set Permanent property after adding filter globally?
Something like this:
`
            services.AddMvc(
                opt =>
                {
                    opt.Filters.Add(typeof (RequireHttpsAttribute));
                });`

Currently I have to create my own wrapper filter. Maybe such filter should be in framework(RequireHttpsPermanentAttribute) or configurable with IOptions?

**Comment by pranavkm** [comment]
@ShadowDancer, you should be able to add an instance of the attribute to the filter collection:
`opt.Filters.Add(new RequireHttpsAttribute { Permanent = true })`

**Pull request merged**
