### PR TITLE
Use latest Mono (v4.0.1) for Travis CI

### PR DESCRIPTION
**Pull request by henkmollema**
Addresses the MyGet 'unknown header' error.

https://github.com/aspnet/dnx/pull/2113

### CODE REVIEW

**Comment by Eilon** [comment]
@sornaks any thoughts on this? Also @BrennanConroy because you were also looking at some Mono stuff.

**Comment by BrennanConroy** [comment]
4.0.1 is fairly good, and its what people get by default so it would be good to run on it. Someone should look at the failures on travis before we decide to use this.

**Comment by sornaks** [comment]
As discussed with @NTaylorMullen the other day, I was going to make travis run against their alpha feed. (4.0.2) That way we have more of their fixes. Once there is an official mono release with fixes to all the bugs which we have filed (most of the fixes are checked in their branch but we do not have an official release) we could move to their official release (from alpha). @Eilon what do you think?

**Comment by Eilon** [comment]
@sornaks yeah I think we might as well try that. More fixes == better as far as I'm concerned.

**Pull request closed without merging**
