### PR TITLE
Summary of the changes related to issue #7845 

### PR DESCRIPTION
**Pull request by jmhmaine**
Summary of the changes:

 - Do not include integrity attribute when asp-fallback-integrity-check is false

 - Added Unit Tests, manual tests

Addresses #7845

### CODE REVIEW

**Comment by jmhmaine** [comment]
@mkArtakMSFT , any suggestions to resolve? I found during testing that I had to rebuild to pass the antiforgery tests. How do we make sure that occurs before the automated tests are run?

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen, can you please help out @jmhmaine? Thanks!

**Comment by NTaylorMullen** [comment]
> @mkArtakMSFT , any suggestions to resolve? I found during testing that I had to rebuild to pass the antiforgery tests. How do we make sure that occurs before the automated tests are run?

Do you see the same issue if you `git clean -xdff` => run `./build.cmd` from the command line?

**Comment by NTaylorMullen** [comment]
Also, @jmhmaine you'll probably need to regenerate some baselines in the functional tests (the CI builds seem to be failing).

You can re-generate baselinese by doing:
1. Remove the `__RemoveThisBitTo__` [here](https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNetCore.Mvc.FunctionalTests/Microsoft.AspNetCore.Mvc.FunctionalTests.csproj#L8).
2. Re-run the tests.
3. Re-add `__RemoveThisBitTo__`

**Comment by jmhmaine** [comment]
@NTaylorMullen, the errors related to pages I had updated were resolved, but it is still failing on calls to pages I didn't update such as Page_SimpleForms_RenderAntiforgery -- which was last updated by you a year ago.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen, will you be able to fix the failing tests (assuming it'll take very little time)? That will allow us to move forward with this PR.

**Comment by NTaylorMullen** [comment]
@jmhmaine thanks for the work in this PR. I'll start fixing it up for inclusion in the MVC repo. I plan to do the following prior to merging:
- Fix up a few tests
- Fix up a few code styling pieces
- Squash your commits but keep your name associated with the 1 commit that represents everything in this PR.
- Change up a few details for clarity sake
- Mention you in the final batch of changes so you can see which things changed.

**Comment by pranavkm** [comment]
@NTaylorMullen could this be closed since https://github.com/aspnet/Mvc/commit/8a77ed23d344c7e438d2772016be3c95f5291ae5 was merged?

**Comment by NTaylorMullen** [comment]
Merged as part of https://github.com/aspnet/Mvc/pull/7904

**Pull request closed without merging**
