### PR TITLE
[Fixes #4152] Add HttpOptionsAttribute

### LINKED ISSUE #4152: HttpOptionsAttribute
I have been converting a project from ASP.NET WebAPI to MVC 6. One issue I found is that there is not HttpOptionsAttribute.

While this is very easy for me to implement myself. I would have thought that this would have been provided out of the box. Is there a reason this isn't implemented? If not can this be implemented.

### PR DESCRIPTION
**Pull request by javiercn**

### CODE REVIEW

**Comment by rynowak** [comment]
:shipit:

**Comment by Eilon** [comment]
No tests?

Can you add to:
* https://github.com/aspnet/Mvc/blob/25eb50120eceb62fd24ab5404210428fcdf0c400/test/Microsoft.AspNetCore.Mvc.Core.Test/Routing/HttpMethodProviderAttributesTests.cs
* https://github.com/aspnet/Mvc/blob/25eb50120eceb62fd24ab5404210428fcdf0c400/test/Microsoft.AspNetCore.Mvc.Core.Test/Routing/RouteTemplateProviderAttributesTest.cs

**Comment by javiercn** [comment]
@Eilon Done 75df24e357e3cdad90ad33dc818a65a2ed299466

**Comment by Eilon** [comment]
Thanks!

**Pull request merged**
