### PR TITLE
Update StringHelper.cs

### PR DESCRIPTION
**Pull request by femiot**
Added Truncate method to shorten given string value.

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@femiot__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, MSOTBOT;

**Comment by Eilon** [comment]
@femiot what is this helper for? These helpers are all internal so unless any part of MVC needs it, there's no value adding it here.

**Comment by femiot** [comment]
I see. How do I know what needs to be added to the project. Are there any documentation to look at? Thanks.

**Comment by Eilon** [comment]
@femiot looking at open issues is one way. We sometimes mark bugs with the [up-for-grabs](https://github.com/aspnet/Mvc/issues?q=is%3Aopen+is%3Aissue+label%3Aup-for-grabs) label if we think it's an issue that is more easily approachable by someone new to the code. You can try to look for this same label in other repos as well.

**Pull request closed without merging**
