### PR TITLE
Remove usage of `async void` in unit tests

### PR DESCRIPTION
**Pull request by rynowak**
Yes I know xUnit supports it, but it's non-standard and it shouldn't show
up anywhere in our codebase.

### CODE REVIEW

**Comment by rynowak** [comment]
FYI only - will merge

**Comment by pranavkm** [comment]
Actually xunit doesn't support it. It doesn't have any magic to wait for the Task to complete, so these could be failing in the background and we would have never known.

**Comment by rynowak** [comment]
Oh, I thought that was what their custom sync context was for.

**Comment by pranavkm** [comment]
Huh, maybe xunit 2.0 does. The 1.x runner did not.

**Pull request merged**
