### PR TITLE
Merge 2.0.2 to dev

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
@dougbu \ @jbagga confirming that your patch changes are already in dev. I'm merging 2.0.2 back in to dev, and there were merge conflicts around `UseDateTimeLocalTypeForDateTimeOffset` and `EnableRangeProcessingSwitch` which resulted in no product change in dev.

**Comment by dougbu** [comment]
@pranavkm I'm not sure either of my changes should show up in this merge. The description for the "Auto-select `type="text"` for `DateTimeOffset` values"" commit mentions
> cherry-picked from 7e4a8fe in dev

And, the "Add Switch.Microsoft.AspNetCore.Mvc.UseDateTimeTypeForDateTimeOffset quirks mode" commit should not come into a non-patch release. Those switches are for patches only.

**Comment by pranavkm** [comment]
Sure, the patch only changes were resolved as part of the merge. I just needed to confirm that those changes were already in dev. 
Merging the patch branch makes it much easier to validate that we're picking up all the patch changes in our mainline branch.

**Comment by natemcmaster** [comment]
LGTM. :shipit: when you've verified there are no other product changes that need merging back into dev

**Comment by jbagga** [comment]
The `EnableRangeProcessingSwitch` is also only meant for the patch. We made other changes in dev regarding that issue. See 0a21d046749ca7ec173504ba694269b446b53324

**Pull request merged**
