### PR TITLE
Fix newline in HtmlHelperSelectExtensions.cs

### PR DESCRIPTION
**Pull request by haruair**
Small fix in `HtmlHelperSelectExtensions.cs`.

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@haruair__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, MSOTBOT;

**Comment by dougbu** [comment]
:shipit: 

@haruair thanks for catching this typo.  I'll get the change in shortly.

fyi your branch is about 65 commits behind the current dev branch.  in the future please rebase on the latest prior to opening a PR.  (of course that's 65 commits done without catching this :smiley_cat: )

**Comment by dougbu** [comment]
fefad34

**Comment by haruair** [comment]
Thanks. I will do rebase my repo.

**Pull request closed without merging**
