### PR TITLE
Fixing local parameter usage

### PR DESCRIPTION
**Pull request by sebastienros**
The argument should be used instead of the property.

### CODE REVIEW

**Comment by rynowak** [comment]
What's the bug?

**Comment by sebastienros** [comment]
It's using a mix of the argument parameter and the class one. In this case I assume the goal is to use the argument, or there is no point in passing it. I'll show you tomorrow if you don't understand, look closely at the case of the variable.

**Comment by rynowak** [comment]
I understand the change you made to the code. Is there a bug here?

The change should probably refactor the code further.

**Comment by dougbu** [comment]
The parameter is passed only because the single caller needs that parameter to determine whether or not `_ViewStart.cshtml` files are relevant. I.e. the method isn't called unless `ViewStartPages == viewStartPages`.

Could certainly change the calling method to instead have a `invokeViewStarts` parameter and use `ViewStartPages` (the property) everywhere. But there's no bug here.

**Comment by Eilon** [comment]
@sebastienros @rynowak @dougbu can you guys figure out what the full fix is for this and update the PR?

**Comment by dougbu** [comment]
My suggestion is (in a bit more detail):
- use `ViewStartPages` throughout `RazorView` e.g. remove `viewStartPages` parameter from `RenderViewStartsAsync()`.
- change `RenderPageAsync()` to instead have a `bool invokeViewStarts` parameter
- call `RenderPageAsync()` with `invokeViewStarts: true` from `RenderAsync()` and `invokeViewStarts: false` from `RenderLayoutAsync()`

**Comment by sebastienros** [comment]
Nothing to add on this PR, I just wanted to point out that the wrong variable name was used. Feel free to close this PR and open a new issue if there is a more general problem with this class.

**Comment by Eilon** [comment]
@dougbu can you do the deed?

**Comment by dougbu** [comment]
:ok:

**Pull request closed without merging**
