### PR TITLE
Enabled coreclr for functional tests and reverted back previous change t...

### LINKED ISSUE #1987: Investigate xml serializer test failures in Core CLR
https://github.com/aspnet/Mvc/commit/f474f7116af0d0c33f93e70fed13c3c2abf70082

### PR DESCRIPTION
**Pull request by kichalla**
...o skipped tests.

- skipped a new test. This is a known issue that I have reported to the respective team.
- This also fixes #1987 : Investigate xml serializer test failures in Core CLR

@rynowak

### CODE REVIEW

**Comment by rynowak** [comment]
:shipit: for re-enabling these. 

Can you please log/link bug a for the issue that's block `CheckIfObjectIsDeserializedWithoutErrors`. I want to make sure that we have something in face that tracks it.

**Comment by kichalla** [comment]
Sure @rynowak

**Comment by kichalla** [comment]
TFS bug id for the failing test : 1140832

**Comment by rynowak** [comment]
Please open a bug in our repo explaining what's broken and link to the TFS bug. We can't point users to TFS bugs, and they aren't actionable for our team

**Comment by kichalla** [comment]
@rynowak : This issue got fixed in coreclr and it does not repro anymore. Will re-enable the test and send out a PR.

**Pull request merged**
