### PR TITLE
Make GetAttributeAdapter virtual

### PR DESCRIPTION
**Pull request by khellang**
This allows you to replace `IValidationAttributeAdapterProvider` with a custom implementation that derives from the default implementation and call the base method.

### CODE REVIEW

**Comment by dougbu** [comment]
@khellang this class is intentionally in an `.Internal` namespace, not something we think is ready for users to build on.

What is your scenario or the issue you'd like to address? Away from the detail of delegating to the default implementation, there might be another way...

If the right approach is to delegate to the default, you don't need to be aware of the `ValidationAttributeAdapterProvider` type. E.g. can use the configured default in DI:
``` c#
services.TryAddSingleton<IValidationAttributeAdapterProvider>(s =>
{
    var defaultProvider = s.GetRequiredService<IValidationAttributeAdapterProvider >();
    return new MyValidationAttributeAdapterProvider(defaultProvider);
});
```

**Comment by khellang** [comment]
Is that the way to "decorate" default services? The reason I wanted the method to be virtual is that I wanted to add a custom attribute (and its corresponding adapter) while still leveraging the Data annotations infrastructure. I found the easiest way was to replace the adapter provider. Have you thought about an API to add custom attributes (and adapters) more easily in the future? It would be nice if there was a super easy way to customize this thought the IMvc(Core)Builder APIs.

**Comment by dougbu** [comment]
> Is that the way to "decorate" default services?

Depends on whether the default implementation is solid enough to be in a public namespace. In this case it isn't, so...

> an API to add custom attributes (and adapters) more easily in the future?

We've definitely thought about this but the exact extensibility point we'd like to provide for this scenario hasn't been designed. The MVC 5 approach of `static` registration methods and so on was a tad ugly and doesn't fit well here.

**Comment by Eilon** [comment]
@dougbu / @khellang any further thoughts on this?

**Comment by khellang** [comment]
Let's close this and come up with a first-class API for adding/extending validation adapters. This can be done by decorating the existing service, like @Doug but showed...

**Pull request closed without merging**
