### PR TITLE
Add convenience overloads for AddControllersAsServices

### PR DESCRIPTION
**Pull request by khellang**
What the title says :dancers: 

This adds one overload for adding assemblies, taking a `TAssembly`, which will add a single assembly based on the type argument.

It also adds a `params` overload for both assemblies and types :sparkles:

Is that something you'd be interested in?

### CODE REVIEW

**Comment by khellang** [comment]
I'm not a fan of the copy-pasta between the `IMvcBuilder` and `IMvcCoreBuilder` extensions. Why does this separation exist? Can't `IMvcBuilder` implement `IMvcCoreBuilder`?

**Comment by rynowak** [comment]
Yes, we're definitely interested is in this. I'll let others chime in with opinions but seeing code like
```
mvc.AddControllersAsServices<HomeController>()
```

throws me. Do it mean add **HomeController** as a service? That's why I don't like it. (and yes, I've seen this before and I am familiar with the pattern).


> I'm not a fan of the copy-pasta between the IMvcBuilder and IMvcCoreBuilder extensions. Why does this separation exist? Can't IMvcBuilder implement IMvcCoreBuilder?

Such things are necessary. `IMvcBuilder` isn't a superset, and you might have implementations that differ in what features are available or required across both experiences.

**Comment by khellang** [comment]
> I'll let others chime in with opinions but seeing code like [...] throws me.

Yes, me too, actually. I just stuck with the name for now. Do you want to see it removed, or just renamed? I've see the `FromAssemblyOf<T>` naming around often. Would that make sense?

**Comment by rynowak** [comment]
If we can come up with a good name, it would be nice to have, otherwise remove it. I'll ask around.

```
.AddControllersAsServicesFromAssemblyOf<HomeController>() 
```

Seems just as verbose as
```
.AddControllersAsServices(typeof(HomeController).Assembly);
```

**Comment by khellang** [comment]
> `.AddControllersAsServicesFromAssemblyOf<HomeController>()` seems just as verbose as `.AddControllersAsServices(typeof(HomeController).Assembly);`

Yes. Yes it does. But the former will be taken care of by IntelliSense in many cases, and the latter will also need `.GetTypeInfo()` before `.Assembly` :smile:

**Comment by danroth27** [comment]
The behavior of specifying a single example type in order to specify an entire assembly feels weird and I think that's why there really isn't a good name for this method. I don't think we should have a method with this behavior - it will just cause confusion.

**Comment by khellang** [comment]
@danroth27 It's a really common pattern across all kinds of libs, so it can't be *that* weird :wink: I even think Entity Framework have (had?) the same kind of methods to "scan" for types in assemblies. Anyway, just say the word and it's gone :sparkles: 

BTW, can any of you shed some light on why these methods exist in the first place? I just stumbled over it when debugging https://github.com/structuremap/structuremap.dnx/issues/6 and found it weird that they didn't exist.

Not having controllers as "services" by default sounds like a really weird default IMO. Especially when you involve a 3rd party container (which is encouraged, right?).

**Comment by danroth27** [comment]
@khellang Can you point me to some examples where this pattern is used? Maybe we can borrow an existing naming convention.

**Comment by khellang** [comment]
- StructureMap has `AssemblyContainingType<T>` (see [source](https://github.com/structuremap/structuremap/blob/da0a94750ba4a1d0f91520e44d2caeec24bff7f3/src/StructureMap.Shared/Graph/AssemblyScanner.cs#L73-L76))
 - Fluent NHibernate has just `AssemblyOf<T>` (see [source](https://github.com/jagregory/fluent-nhibernate/blob/6302b200c349ca5c5c61ad5f829fbf14b9ba123b/src/FluentNHibernate/Automapping/AutoMap.cs#L17-L20))
 - EF Contrib (I thought this was actually pulled into EF proper, but I couldn't find it) has `AddFromAssemblyOf<T>` (see [source](https://ef6contrib.codeplex.com/SourceControl/latest#src/EntityFramework.Contrib/ModelConfiguration/Configuration/ConfigurationRegistrarExtensions.cs))
 - Ninject has `FromAssemblyContaining<T>` (see [source](https://github.com/ninject/Ninject.Extensions.Conventions/blob/d0f2acc2d0ab17e4fdda9698ccc407413a17b56e/src/Ninject.Extensions.Conventions/BindingBuilder/ConventionSyntax.From.cs#L73-L76))
 - FluentSitemap has `FromAsemblyOf<T>` (see [source](https://github.com/khalidabuhakmeh/FluentSitemap/blob/a18308af0b9c93f7f64ce3c0d6823bfd8029ad46/FluentSitemap.Core/SitemapConfigurator.cs#L295-L299))
 - Scrutor has `FromAssemblyOf<T>` (see [source](https://github.com/khellang/Scrutor/blob/2545b16747b81f42c889ec57415e3acc8018f9c0/src/Scrutor/LifetimeSelector.cs#L22-L25))

These are just some that I knew from the top of my head. I'm sure there are others.

**Comment by danroth27** [comment]
OK, despite it's verbosity, `AddControllersAsServicesFromAssemblyOf<HomeController>()` does seem like the logical choice. @rynowak chime in if you and @pranavkm come up with something better.

**Comment by rynowak** [comment]
I haven't come up with anything better. I'm equally happy with `AddControllersAsServicesFromAssemblyOf` or just leaving it out.

**Comment by pranavkm** [comment]
An alternative might be to have a builder for AddControllersAsServices

```C#
IControllerAsAssemblyBuilder AddControllersAsServices(params Type[] controllerTypes)

IControllerAsAssemblyBuilder
{
   AddType();
}
```
We could bake the `FromAssemblyContaining(Type type)` method in or have DI systems provide it as an extension method.

**Comment by rynowak** [comment]
@Eilon  - any thoughts on https://github.com/aspnet/Mvc/pull/3857#issuecomment-169057146 and resulting discussion?

I think that's pretty much the one thing left to discuss here. 

My opinion: leave it out :laughing:

**Comment by Eilon** [comment]
@rynowak yeah leave out for now. Too awkward.

**Comment by rynowak** [comment]
@khellang - any argument from you if I remove the `TAssembly` overloads and merge this bad boy?

**Comment by khellang** [comment]
@rynowak Nope, but that single method was actually the method I was after, and the reason I sent this. Too bad naming is so hard :stuck_out_tongue_closed_eyes: Want me to strip it quickly?

**Comment by rynowak** [comment]
sure

**Comment by khellang** [comment]
Done :+1.

**Comment by rynowak** [comment]
6737a1f243a35e7daed119c40ed6b026382d8fae

**Pull request closed without merging**
