### PR TITLE
Enabling ViewEngine and Localization tests which use expanders. The issues are fixed in the mono beta 4.0.4

### PR DESCRIPTION
**Pull request by sornaks**

### CODE REVIEW

**Comment by pranavkm** [comment]
:shipit:

**Comment by dougbu** [comment]
Am I correct #2759 is actually an External bug and it's ready to be closed?

**Comment by dougbu** [comment]
:shipit:

**Comment by sornaks** [comment]
Yes..

**Comment by sornaks** [comment]
https://github.com/aspnet/Mvc/commit/9915ea38097857cc8046b9cceaec7ad6bd0b9b11

**Pull request closed without merging**
