### PR TITLE
changed GetFormat of FormatFilter to virtual

### PR DESCRIPTION
**Pull request by filipw**
Allows me to use a custom query string (instead of the hardcoded `format`) or extract format in any other funky way from the `ActionContext`.
 
I can now subclass `FormatFilter` with my own implementation of `GetFormat`, register this custom implementation in the DI and then have `FormatFilterAttribute` pick it up automatically.

### CODE REVIEW

**Comment by Eilon** [comment]
@rynowak can you merge?

**Comment by rynowak** [comment]
Merged  f567258f1435da03d7e3d204a7530f0a342fe4e9

**Comment by Eilon** [comment]
@rynowak close?

**Comment by rynowak** [comment]
:grin:

**Comment by filipw** [comment]
thanks

**Pull request closed without merging**
