### PR TITLE
Commit Localization MaxLengthAttribute and compareAttribute

### PR DESCRIPTION
**Pull request by Anderman**
I made a fix for aspnet-5 localization for ErrorMEssage in the MaxLengthAttribute and compareAttribute.

See issue https://github.com/aspnet/Mvc/issues/3527 and all other related issues

### CODE REVIEW

**Comment by Anderman** [comment]
@dougbu Is this the right way todo this?. I can make a fix for other ErrorMessage localization

**Comment by dougbu** [comment]
@Anderman this looks like a solid improvement over what we have today. Main question is about the higher-level design i.e. `params` versus adding the following or some other approach.
``` c#
protected virtual LocalizedString GetLocalizedErrorMessage(string displayName)
{
    return _stringLocalizer[Attribute.ErrorMessage, displayName];
}   
```

@kirthik what fits best with how you've done localization elsewhere?

Separately, should fix `DataAnnotationsModelValidator`s at the same time as the `DataAnnotationsClientModelValidator<TAttribute>`s.

**Comment by Anderman** [comment]
@kirthik the `[EmailAddress]` attribute set Attribute.ErrorMessage. The code use this to chose between    the `_stringLocalizer[]` and the default `Attribute.FormatErrormessage()`

A workaround could be something like this
```
CustomErrorMessageSet = attribute.ErrorMessage != (new DataTypeAttribute(attribute.DataType)).ErrorMessage;
```

Any suggestions?

**Comment by Anderman** [comment]
I found the problem. It is in `System.ComponentModel.DataAnnotations/DataAnnotations/EmailAddressAttribute.cs`

This line was set 28 days ago. But it should not be set at all 
`DefaultErrorMessage = DataAnnotationsResources.EmailAddressAttribute_Invalid;`

**Comment by kirthik** [comment]
@Anderman : You implemented one way of solving this issue. @dougbu suggested another way. I am working on a prototype to address this issue. I will let you know once we have a finalized design.

**Comment by Anderman** [comment]
Oke fine, I created just a issue about the [emailadressAttribute](https://github.com/dotnet/corefx/issues/4481)

**Pull request closed without merging**
