### PR TITLE
Added check for null arguments to GetArgumentDictionary

### PR DESCRIPTION
**Pull request by jbagga**
Is this desired behavior? Or should I instead check for null and skip allocating of a new Dictionary object if `object arguments` is null? 

Addresses #5423 

cc @rynowak

### CODE REVIEW

**Comment by rynowak** [comment]
You should skip allocating the dictionary in the event that there were no arguments provided. It's not a perf change, it's just more correct that way 😆

**Comment by jbagga** [comment]
cc @rynowak Got it. Thanks!

**Comment by jbagga** [comment]
@rynowak Are there some tests already for non-null arguments in functional tests? Should I be adding any to https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNetCore.Mvc.Core.Test/Internal/ControllerActionInvokerTest.cs

**Comment by rynowak** [comment]
We figured out here that there are only functional tests for VCs. This change looks good, we need to include this when we do real functional tests.

**Pull request merged**
