### PR TITLE
Removing 'Options' from ConfigureMvcOptions and ConfigureRazorViewEngineOptions.

### PR DESCRIPTION
**Pull request by sornaks**
https://github.com/aspnet/Mvc/issues/2169

### CODE REVIEW

**Comment by kichalla** [comment]
:shipit:

**Comment by dougbu** [comment]
:shipit:

**Comment by Eilon** [comment]
:shipit: because three's a charm.

**Comment by rynowak** [comment]
:shipit: 4 is a party

**Comment by sornaks** [comment]
Thanks guys! https://github.com/aspnet/Mvc/commit/d2bdd4f1d4096e2387ff2435ef0c0eed1dcb2c53

**Pull request closed without merging**
