### PR TITLE
Throw an exception if configurationType to CreateConfigureDelegate is…

### PR DESCRIPTION
**Pull request by jbagga**
… abstract/has no ctor

@pranavkm  Addresses #5431

### CODE REVIEW

**Comment by davidfowl** [comment]
o we have any other code like this?

**Comment by pranavkm** [comment]
@davidfowl  - something a bit similar - https://github.com/aspnet/Mvc/commit/d09e921c4a896865b0bd81bd99e8e69dc19460b7. @kichalla might have a better idea about if we have other places where we throw if a parameterless ctor doesn't exist.

**Comment by pranavkm** [comment]
@jbagga did you accidentally close this?

**Comment by jbagga** [comment]
@pranavkm There was a merge conflict in the Resources file. I am trying to figure out what was wrong. I'll reopen it once I fix it!

**Comment by jbagga** [comment]
Moved [here](https://github.com/aspnet/Mvc/pull/5517)

**Pull request closed without merging**
