### PR TITLE
Check for empty location in ViewsFeatureProvider

### LINKED ISSUE #5675: NullException in Microsoft.AspNetCore.Mvc.Razor.Compilation.ViewsFeatureProvider.GetViewInfoContainerType
When you load assembly from stream, Assembly.IsDynamic = false and Assembly.Location is empty (not null) so Path.GetDirectoryName(assemblyPart.Assembly.Location) return null...

So :
in file Mvc/src/Microsoft.AspNetCore.Mvc.Razor/Compilation/ViewsFeatureProvider.cs line 61
`if (!assemblyPart.Assembly.IsDynamic && assemblyPart.Assembly.Location != null)`
must be : 
`if (!assemblyPart.Assembly.IsDynamic && !string.IsNullOrEmpty(assemblyPart.Assembly.Location))`

### PR DESCRIPTION
**Pull request by pranavkm**
Fixes #5675

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @Eilon

**Comment by ryanbrandenburg** [comment]
Your code seems pretty straightforward, but I'm wondering under what conditions Assembly.Location would be empty?

**Comment by ryanbrandenburg** [comment]
Looks like you're test's failing though.

**Comment by pranavkm** [comment]
:up: :date: According to the bug, the location is null when an assembly is loaded from a stream.

**Pull request merged**
