### PR TITLE
RemoveRange does not throw for any IEnumerable input.

### PR DESCRIPTION
**Pull request by ajaybhargavb**
Issue - #2491 
@dougbu @Eilon

### CODE REVIEW

**Comment by Eilon** [comment]
:shipit:

**Comment by dougbu** [comment]
:shipit:

**Comment by dougbu** [comment]
but why is AppVeyor build failing?  looks like something related to `IExpirationTrigger` changed.

**Comment by Eilon** [comment]
@dougbu that was a recent rename. Maybe this build hasn't caught up yet. @kichalla was making that change I believe.

**Comment by kichalla** [comment]
:+1: Yes, this was a change I pushed this morning (our CI is green related to this change)

**Pull request merged**
