### PR TITLE
[Merge] XmlDataContractSerializer Input and Output Formatter Tests Cleanup

### PR DESCRIPTION
**Pull request by tonysneed**
This is the final version of #1887 with the original commits squashed down to a single commit.

### CODE REVIEW

**Comment by kichalla** [comment]
Thanks! Anthony...merged the commit to aspnet/dev 1118315a9dac7e86d8b22ea6e192dd1c920df86a

**Comment by tonysneed** [comment]
Creating a separate PR for the rebase seems to be paying off, because I can resolve the conflicts on my end. :sunglasses:  I'm a bit new to git workflows, so let me know if there is a better way. :question:

**Comment by kichalla** [comment]
I am not an expert in Git but some info:
- if you got a sign-off on a PR already, you can squash and re-base your commits and push the changes to the same PR/branch for us to merge them in.
- If you have not got a sign-off on a PR and if you squash and re-base your commits and push them to the same PR, then it would be difficult for the reviewers as several commits of yours have been merged to one...example: if i am a reviewer  I would like to see what were the feedback changes you incorporated since the last commit(example: changes to a single file) instead of seeing one single squashed commit(example: changes to a multiple files).

Adding some git experts for their inputs: @rynowak @pranavkm @harshgMSFT

**Comment by rynowak** [comment]
> Creating a separate PR for the rebase seems to be paying off, because I can resolve the conflicts on my end. :sunglasses: I'm a bit new to git workflows, so let me know if there is a better way. :question:

You tend to create very well isolated commits that make things easy on reviewers which is great. It's totally fine to rebase your own work on your own branch and force push to your existing branch -- better to do that when you've got signoff.

**Comment by tonysneed** [comment]
Cool, so after I've got a sign-off on the PR, I should:
- squash my commits (after first making a backup of the branch)
- pull latest upstream into my local dev branch
- rebase my commit (replay commit onto latest version of dev)
  + resolve conflicts during rebase
- force push to my existing branch
  + make sure to set push.default config setting to simple
- after PR merged and closed, go ahead and delete the branch

I got some info on this kind of workflow from [here] (https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request).

**Pull request merged**
