### PR TITLE
Perf: Check for OPTIONS before looking for CORS headers

### PR DESCRIPTION
**Pull request by ajaybhargavb**
Issue #5016 

@rynowak

### CODE REVIEW

**Comment by ajaybhargavb** [comment]
@rynowak, Is perf data needed?

**Comment by rynowak** [comment]
Can you do a quick profile and see if the headers getting populated still shows up? I'd suggest looking at https://github.com/aspnet/Performance/tree/dev/testapp/HelloWorldMvcCore

**Comment by ajaybhargavb** [comment]
Before:
image


After:
image

**Comment by rynowak** [comment]
You don't have nearly enough data here to indicate anything. Let's talk when you get in.

**Comment by ajaybhargavb** [comment]
Better data:
Running 40000 requests with 2000 rps on an action method with `[HttpGet]` action constraint

Before:
image

After:
image

**Comment by rynowak** [comment]
:shipit: But please add a comment explaining why this was important for performance.

We want to make all of the non-obviousness obvious.

**Pull request merged**
