### PR TITLE
Use `IValidationAttributeAdapterProvider`

### PR DESCRIPTION
**Pull request by dougbu**
- #5009
- don't create a `RequiredAttributeAdapter` directly

### CODE REVIEW

**Comment by dougbu** [comment]
Reviewers, no reason to test whether implementation uses given provider from my perspective. Please let me know if you disagree for this particular (special) case.

**Comment by pranavkm** [comment]
If it's not super hard, wouldn't hurt to get a test in for this.

:shipit:

**Comment by dougbu** [comment]
> If it's not super hard, wouldn't hurt to get a test in for this.

:see_no_evil:

**Comment by dougbu** [comment]
35cc5b6

**Pull request closed without merging**
