### PR TITLE
RazorPage.User should be ClaimsPrincipal

### PR DESCRIPTION
**Pull request by ianhong**
@HaoK , @davidfowl , and @NTaylorMullen 
This is a PR for #2167.

Amazingly, this was one line change. I checked MusicStore, Scaffolding, Entrophy. It looks like there should be no react to the other repros. 

Once this is checked in, I'll monitor the CI machine to make it sure.

Thanks,

### CODE REVIEW

**Comment by NTaylorMullen** [comment]
As long as it builds, looks good :smile:  :shipit:

**Comment by ianhong** [comment]
@HaoK, could you review this?? It is a very simple PR..ever..:-)

**Comment by HaoK** [comment]
:shipit:

**Comment by Eilon** [comment]
:shipit:

**Comment by ianhong** [comment]
ee49ab727f54b815aecc6bb998610f69c035d3d3

**Pull request closed without merging**
