### PR TITLE
remove redundant dependencies in sample

### PR DESCRIPTION
**Pull request by Kagamine**
Due to https://github.com/aspnet/Announcements/issues/69
There is no need to use Microsoft.AspNet.Server.IIS

### CODE REVIEW

**Comment by pranavkm** [comment]
@NTaylorMullen could you re-run the Travis builds?

**Comment by NTaylorMullen** [comment]
re-running now

**Comment by JunTaoLuo** [comment]
@Kagamine be careful with pushing that many times in quick succession, it creates tons of test builds on travis and can hog up the testing resources.

**Comment by Kagamine** [comment]
@JunTaoLuo  Sorry...

**Comment by Eilon** [comment]
@Kagamine can you squash the commits into one?

**Comment by Eilon** [comment]
Sorry nevermind, didn't realize this is closed...

**Comment by Kagamine** [comment]
@Elion I have created new one https://github.com/aspnet/Mvc/pull/3224
Use the IISPlatformHandler instead of the old IIS Server.

**Pull request closed without merging**
