### PR TITLE
Remove Microsoft.AspNet.Server.IIS

### PR DESCRIPTION
**Pull request by Kagamine**
In this PR, I removed the package Microsoft.AspNet.Server.IIS, because Microsoft.AspNet.Server.IIS is too old. 

/cc @pranavkm @Eilon @NTaylorMullen @dougbu

### CODE REVIEW

**Comment by Eilon** [comment]
@pranavkm

**Comment by Kagamine** [comment]
@pranavkm

**Comment by pranavkm** [comment]
Sorry I was caught up with some other work. I'll get this merged in.

**Comment by Kagamine** [comment]
Oops. I didn't skilled rebase... It looks that I made lots of mistakes.

**Comment by Kagamine** [comment]
I will create another PR and close this, sorry.

**Comment by Kagamine** [comment]
@pranavkm 3405 opened

**Comment by pranavkm** [comment]
Thanks

**Comment by pranavkm** [comment]
Merged in https://github.com/aspnet/Mvc/commit/38818a103340b82f8deaed5900f4b6a97e8b3e50

**Pull request closed without merging**
