### PR TITLE
[feature] Checkboxes for collections and value id attributes for radio buttons

### PR DESCRIPTION
**Pull request by artiomchi**
For a while now generating multiple radio buttons with labels has been somewhat troublesome, since all the radio buttons would get the same `id` attribute, and we had to manually pass an id attribute in the htmlAttributes anonymous object, then pass the same value to the label's for attribute

Added to this, the checkbox helpers will only create checkboxes for boolean properties. In fact, the tag helpers in asp.net core will throw an exception if a non boolean type is passed to the input helper with type=checkbox

This pull request tries to achieve two things:
1. Append the serialised value of the radio button to it's id attribute to generate a unique id for each radio button
2. Add the ability to create checkboxes for collection properties, and generate unique ids for each
3. Extend the label tag helper to generate the same ids as above, to simplify debelopment

Specifically, given this model classes:

```
public class EditModel
{
    public int ID { get; set; }
    public int[] Roles { get; set; }
    public Gender Gender { get; set; }

    public Role[] AllRoles() => new[]
    {
        new Role { ID = 1, Title = "Role 1" },
        new Role { ID = 2, Title = "Role 2" },
    };
}

public class Role
{
    public int ID { get; set; }
    public string Title { get; set; }
}

public enum Gender
{
    Male = 1,
    Female = 2,
}
```

And this razor view:

```
<li>
    <label>Gender</label>
    @foreach (Gender gender in Enum.GetValues(typeof(Gender)))
    {
        <input asp-for="Gender" type="radio" value="@gender" />
        <label asp-for="Gender" asp-for-value="@gender">@gender</label>
    }
    <input asp-for="Gender" type="radio" value="@Gender.Male" id="Gender_Male_Custom" />
    <label asp-for="Gender" for="Gender_Male_Custom">@Gender.Male (custom id)</label>
</li>
<li>
    <label>Roles</label>
    @foreach (var role in Model.AllRoles())
    {
        <input asp-for-collection="Roles" type="checkbox" value="role.ID" />
        <label asp-for="Roles" asp-for-value="role.ID">@role.Title</label>
    }
    <input type="checkbox" name="Roles" value="3" id="Roles_3" />
    <label for="Roles_3">Role 3 (custom id)</label>
</li>
```

Generates the following:

```
<ul>
    <li>
        <label for="ID">ID</label>
        <input type="number" data-val="true" data-val-required="The ID field is required." id="ID" name="ID" value="0">
    </li>
    <li>
        <label>Gender</label>
        <input type="radio" value="Female" data-val="true" data-val-required="The Gender field is required." id="Gender_Female" name="Gender">
        <label for="Gender_Female">Female</label>
        <input type="radio" value="Male" id="Gender_Male" name="Gender">
        <label for="Gender_Male">Male</label>
        <input type="radio" value="Male" id="Gender_Male_Custom" name="Gender">
        <label for="Gender_Male_Custom">Male (custom id)</label>
    </li>
    <li>
        <label>Roles</label>
        <input id="Roles_1" name="Roles" type="checkbox" value="1">
        <label for="Roles_1">Role 1</label>
        <input id="Roles_2" name="Roles" type="checkbox" value="2">
        <label for="Roles_2">Role 2</label>
        <input type="checkbox" name="Roles" value="3" id="Roles_3">
        <label for="Roles_3">Role 3 (custom id)</label>
    </li>
</ul>
```

**UPD:** Updated the last code sample, since the checkboxes have to be generated with custom values, not booleans

### CODE REVIEW

**Comment by artiomchi** [comment]
A couple notes regarding the implementation:

- I've created the `CollectionCheckboxTagHelper` instead of extending the `InputTagHelper` for a couple reasons, but mainly because I wanted the Value property to be of type `object`. This way I could compare the actual values in the Array, rather than converting them to strings when testing which checkbox should be checked. ( basically for this: [line 100 in CollectionCheckboxTagHelper.cs](https://github.com/artiomchi/Mvc/blob/985413eddd036c3faf1a8a1d367f57c38bb9178b/src/Microsoft.AspNetCore.Mvc.TagHelpers/CollectionCheckboxTagHelper.cs#L100))
- By default all radio buttons will use the new behaviour of their values being appended to their id attributes. After some deliberation, I've though that this would be the preferred behaviour, since generating multiple elements (radio buttons) with the same id attribute is pretty useless anyway, and wouldn't work when trying to access them from js.

**Comment by dougbu** [comment]
Did not look at this in detail but it raises a few back compat concerns e.g.
- Different HTML generation for existing functional tests -- different `id` values for `<input type='radio' ... />` fields.
- Changes to the `IHtmlGenerator` interface, which is `public` albeit in a little-used namespace.

**Comment by artiomchi** [comment]
Regarding changes to `IHtmlGenerator` - I see how this could cause backwards compatibility issues. What I could do is add an overload that has the new parameter, leaving the current method signature intact, and as such - backwards compatible. I was initially going to mark the parameter optional, but if the method is used in a lambda (like in the test projects), it causes an exception.

Regarding different html generated - I don't think that's as big a problem, since the previously generated html was actually bad in the first place, since it generated multiple elements with the same id attribute. I've updated the aspnet/mvc functional tests so that they run successfully (travis ran it twice, one of them failed for seemingly unrelated reasons), and if someone else's project tests fail because of this change, after they upgrade the libraries, it's a trivial change to update them to the new input id values.

**Comment by mkArtakMSFT** [comment]
Hi @artiomchi. Sorry for our late response on this.
As a lot of time has passed since this PR has been opened, there are a lot of conflicts already, so we're going to close this PR.

**Comment by pranavkm** [comment]
Had a chance to look at this, but the PR needs a bunch of work outside of just cleaning up the merge conflicts. There's already another issue tracking the work to support a list or group of checkboxes and radio buttons here - https://github.com/aspnet/Mvc/issues/599. We'll use that to drive the remainder of work

**Pull request closed without merging**
