### PR TITLE
[Fixes #1536] Added activation tests for tag helpers

### LINKED ISSUE #1536: Tag Helpers: We need additional functional tests for verifying activation of TagHelpers
There're extensive test in ActivationWebsite around what works and what does not with activation. We need to ensure there's sufficient coverage for TagHelpers in this area.

### PR DESCRIPTION
**Pull request by ajaybhargavb**
@NTaylorMullen

### CODE REVIEW

**Comment by rynowak** [comment]
@pranavkm @dougbu can you take a look?

**Comment by ajaybhargavb** [comment]
Updated.

**Comment by NTaylorMullen** [comment]
:shipit:

**Comment by dougbu** [comment]
:shipit:

**Pull request merged**
