### PR TITLE
Add `enum`-related details to `ModelMetadata`

### PR DESCRIPTION
**Pull request by dougbu**
- #438 part 1/2 and #2027 part 1/3 (all small)
- needs tests and XML doc corrections (broken references)

### CODE REVIEW

**Comment by rynowak** [comment]
Looks to be on the right track. I have some idea about how to clean up the cachability of this, but it can wait until later.

**Comment by dougbu** [comment]
Updated to include tests and removed [Design] label

@rynowak any objection to the third commit I added?

**Comment by rynowak** [comment]
> @rynowak any objection to the last commit I added (USE_REAL_RESOURCES)?

No objection, I just don't see what it fixes. We're testing that we call the correct overload of `DisplayAttribute` so it will use reflection to call a static property on a static class. It seems super-insignificant to me what that static property does for the purposes of the test (we mock things constantly).

I also don't see why/how we'd enable `USE_REAL_RESOURCES` as a define in the future. Basically IMO this just creates more ceremony on something we'd do 100% of the way in a perfect world. Due to limitations in our tests, we went 95% and to me that's good enough.

If you feel like this is worth it go ahead. :shipit: from me on the changes that actually related to the enum feature.

**Comment by dougbu** [comment]
@rynowak to be clear, there's no "limitations" in our tests in this area.  I added `USE_REAL_RESOURCES` only to make it easy (a one-line addition to project.json) to test any workaround for the `[Display]` limitation we might come up with.  I agree that if we were successful, we'd remove `TestResources` and update the few places where we use `USE_REAL_RESOURCES`.

**Comment by dougbu** [comment]
commit 7dd3afe

**Comment by rynowak** [comment]
@dougbu :ok_hand: if you think it's better got for it!

**Pull request closed without merging**
