### PR TITLE
Flags enum support for some select-related classes (see #3977)

### PR DESCRIPTION
**Pull request by tuespetre**
Intended to build upon #3995, although that commit is not included in this PR.
- Allow use of `GetEnumSelectList` helpers with Flags enums
  - The test data for the related tests was very strange, as all of the test methods were accepting three parameters but only using one. I discerned which tests were using which parameters and split the test data out to make things a little more straightforward.
- Make `DefaultHtmlGenerator` detect multiple values for Flags enums
  - I did reorder a small handful of test data parameters related to this just because they were coded to expect a trimmed value first before an untrimmed value. I am not sure if this is anything significant or not.
  - This is using the old `private static readonly IDictionary<Type,Delegate>` trick to cache the delegates used to squeeze the current values out of an enum value. I'm not sure how friendly everyone is towards that pattern.
- Remove `EnumNamesAndValues` from metadata classes
  - Though this was technically a `public` item, the only place it was used was during `GetCurrentValues` in the `DefaultHtmlGenerator`. It was kind of an awkward property and the one place it was used did not seem performance-friendly. At first I thought maybe it held the `[Display]` text for the enum values but that did not seem to be the case.
- Make `<select>` tag helper behave as `<select multiple>` with Flags enums
  - Perhaps the tag helper should only behave this way with a Flags enum if the 'multiple' attribute is actually present? Or maybe the tag helper should strictly require the 'multiple' attribute to function as a multi-select and throw an exception if the model type is invalid?

### CODE REVIEW

**Comment by Eilon** [comment]
@tuespetre at this time we are not planning to take this feature because we are working on stabilizing the RC2 release. We will revisit this in the next release.

**Comment by tuespetre** [comment]
Thanks @Eilon; question for you and probably @rynowak / @dougbu: what's up with the `EnumNamesAndValues` property on the metadata? As it stands it seems to be part of the 'public API' but as I mentioned in this PR it doesn't seem to be used anywhere besides one place, and in that one place it seems like it would have an unnecessary performance impact (uses LINQ when it doesn't need to, etc.)

In my mind, that is closely related to #3953; I was just curious about this and wondering if you had some other reason for it to be part of the 'public API'.

**Comment by rynowak** [comment]
> As it stands it seems to be part of the 'public API' but as I mentioned in this PR it doesn't seem to be used anywhere besides one place

I seem to recall this was added to support that one place it's used :+1: The `ModelMetadata` is a cache of stuff that could be derived from reflection + attributes. The list of display-names for enum values is really independent of how we render HTML for an enum, hence the layering.


> it seems like it would have an unnecessary performance impact

What code are you talking about specifically? Our approach with perf is to measure first. Lot's of code has an 'unnecessary' cost - but generally we're looking for the right tradeoffs.

Is this code much more readable as is? [This method](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Internal/FilterCache.cs#L136) used to be about 5 lines before we ran into the need to optimize it :+1: 

Does this code have an impact in the big picture (in a real application)?

If it's something trivial like turning a linq into the equivalent looping construct and it runs on every request, and it's not a big decrease in readability, then it seems like a good idea.

**Comment by dougbu** [comment]
> ... it runs on every request ...

The Linq in question runs once per type, not on every request. See [this block](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.DataAnnotations/Internal/DataAnnotationsMetadataProvider.cs#L107-L141) in the `DataAnnotationsMetadataProvider`.

**Comment by tuespetre** [comment]
@rynowak:
> What code are you talking about specifically?
@dougbu:
> The Linq in question runs once per type, not on every request.

This is the code I am talking about; it will run every time the `DefaultHtmlGenerator` gets the current values for a given model expression:

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/DefaultHtmlGenerator.cs#L1023

> If it's something trivial like turning a linq into the equivalent looping construct and it runs on every request, and it's not a big decrease in readability, then it seems like a good idea.

That's about what it would be; if `EnumNamesAndValues` was also a `IReadOnlyDictionary<string, Enum>` instead, it would eliminate the need to compare string values.

> I seem to recall this was added to support that one place it's used :+1: The ModelMetadata is a cache of stuff that could be derived from reflection + attributes. The list of display-names for enum values is really independent of how we render HTML for an enum, hence the layering.

Thanks for the explanation. There's also this guy here, maybe it could be a cached delegate stored in the `ModelMetadata`:

https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/DefaultHtmlGenerator.cs#L1007

**Comment by dougbu** [comment]
@tuespetre are you seeing any of this Linq in performance measurements? Separately we'd have to be very careful about caching at either site you linked to: Values change per request.

**Comment by tuespetre** [comment]
> @tuespetre are you seeing any of this Linq in performance measurements? Separately we'd have to be very careful about caching at either site you linked to: Values change per request.

To be honest I haven't; I have had issues with trying to get the performance benchmarks going like we discussed on #3953. I may try that again sometime today or tonight depending on how things go. As for the caching bit, it would just be caching a delegate instead of generating one with `MakeGenericMethod()` each time.

I think I will try to get those benchmarks going again later and pick up this discussion back over on #3953. Thanks!

**Comment by Eilon** [comment]
Re-opening because we are still considering this.

**Comment by mkArtakMSFT** [comment]
Hi @tuespetre. Sorry for our late response on this.
As a lot of time has passed since this PR has been opened, there are a lot of conflicts already, so we're going to close this PR.

**Pull request closed without merging**
