### PR TITLE
Move PageExecutionListener interfaces to a separate assembly.

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @davidfowl

**Comment by Eilon** [comment]
What's the motivation for this?

**Comment by pranavkm** [comment]
With ANIs going away, we need a single assembly that Razor and browser link can reference.

**Comment by yishaigalatzer** [comment]
:shipit:

**Comment by Eilon** [comment]
Thanks for the explanation!

**Pull request closed without merging**
