### PR TITLE
Reacting to Hosting changes

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @JunTaoLuo \ @NTaylorMullen \ @ajaybhargavb

**Comment by JunTaoLuo** [comment]
:shipit: after removing all the wwwroot from project.json

**Comment by NTaylorMullen** [comment]
Looks solid to me. 100% consistent with what I did in [mine](https://github.com/aspnet/Mvc/pull/3792/files).

:shipit:

**Comment by JunTaoLuo** [comment]
:ship:

**Comment by pranavkm** [comment]
Updated to fix `MvcTestFixture`

**Pull request merged**
