### PR TITLE
Update to dev versions

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @ryanbrandenburg \ @NTaylorMullen \ @ajaybhargavb 

Could you guys have a look? I'm not sending a PR to individual repos. It'd be nice to have some eyes on the change before I bulk push.

**Comment by ryanbrandenburg** [comment]
1.0.0-* -> 1.1.0-* :shipit:

**Comment by javiercn** [comment]
:shipit:

**Comment by ajaybhargavb** [comment]
:shipit:

**Comment by Eilon** [comment]
And... :shipit: 😄

**Pull request closed without merging**
