### PR TITLE
[Fixes #5463] JsonPatchDocument.ApplyTo With ModelState Throws Exceptions

### LINKED ISSUE #5463: JsonPatchDocument.ApplyTo With ModelState Throws Exceptions
The overload of `ApplyTo` with `ModelState` throws exceptions:
- `ArgumentException` when the patch document is invalid e.g. empty `op` property or typo in the `op` property.
- `InvalidOperationException` when using a value of `test` for the `op` property.

I expected it to add an error into the `ModelState` instead. Right now, I'm having to wrap it in a try-catch and add `ModelState` errors manually.

I've resorted to writing the following extension method to add errors instead of throw exceptions:

```
public static class JsonPatchDocumentExtensions
{
    public static void SafeApplyTo<T>(this JsonPatchDocument<T> patch, T value, ModelStateDictionary modelState)
        where T : class
    {
        try
        {
            patch.ApplyTo(value, modelState);
        }
        catch (ArgumentException argumentException)
        {
            modelState.AddModelError(
                typeof(T).Name,
                argumentException.Message);
        }
        catch (NotSupportedException notSupportedException)
        {
            modelState.AddModelError(
                typeof(T).Name,
                notSupportedException.Message);
        }
    }
}
```

Unit tests:

```
public class JsonPatchDocumentExtensionsTest
{
    [Fact]
    public void SafeApplyTo_ValidPatchParameters_NoErrorsAdded()
    {
        var patch = new JsonPatchDocument<Model>();
        patch.Operations.Add(new Operation<Model>("replace", "/Property", null, "Foo"));
        var model = new Model();
        var modelState = new ModelStateDictionary();

        patch.SafeApplyTo(model, modelState);

        Assert.Equal(0, modelState.ErrorCount);
    }

    [Theory]
    [InlineData("replace", "/PropertyNotFound", null, "Foo", "The property at path '/PropertyNotFound' could not be removed.")]
    [InlineData("test", "/Property", null, "Foo", "The test operation is not supported.")]
    [InlineData("invalid", "/Property", null, "Foo", "Requested value 'invalid' was not found.")]
    [InlineData("", "/Property", null, "Foo", "Must specify valid information for parsing in the string.")]
    public void SafeApplyTo_PatchParameters_AddsModelStateError(
        string op,
        string path,
        string from,
        string value,
        string error)
    {
        var patch = new JsonPatchDocument<Model>();
        patch.Operations.Add(new Operation<Model>(op, path, from, value));
        var model = new Model();
        var modelState = new ModelStateDictionary();

        patch.SafeApplyTo(model, modelState);

        Assert.Equal(1, modelState.ErrorCount);
        Assert.Equal(nameof(Model), modelState.First().Key);
        Assert.Equal(1, modelState.First().Value.Errors.Count);
        Assert.Equal(error, modelState.First().Value.Errors.First().ErrorMessage);
    }

    public class Model
    {
        public string Property { get; set; }
    }
}
```

### PR DESCRIPTION
**Pull request by kichalla**
Related PR: https://github.com/aspnet/JsonPatch/pull/46

### CODE REVIEW

**Comment by rynowak** [comment]
what about this statement from the bug:

> ArgumentException when the patch document is invalid e.g. empty op property or typo in the op property.

Are there other kinds of things we should test?

**Comment by kichalla** [comment]
> Are there other kinds of things we should test?

I do not think so as there are basically 3 areas for exceptions here from what I have investigated:
1. Deserialization into JsonPatchDocument or its generic version. These errors should already be in the ModelState.
2. User calling `ApplyTo` on the JsonPatchDocument. (This should be fixed with the current PR)
3. Exceptions that happen due to invalid data (ex: Invalid 'path' in the operation). [This is already handled by ObjectAdapter]

**Comment by rynowak** [comment]
Ok thanks, these tests seem ready to go :shipit:

**Comment by kichalla** [comment]
047def1aaf097b080b899fd829f4f47d53bf16c8

**Pull request closed without merging**
