### PR TITLE
Specify route name to UrlHelper Action Method

### PR DESCRIPTION
**Pull request by pushist1y**
If there is more than one named route - allows to specify which one to use for generating the url.

### CODE REVIEW

**Comment by pushist1y** [comment]
Also would be useful if you have a single named route and a number of unnamed which you'd like to exclude from url generation.

**Comment by dougbu** [comment]
What is the advantage of the new approach over `IUrlHelper.RouteUrl()`?

**Comment by pushist1y** [comment]
Using named parameters is much more easy and obvious than digging deep inside mvc and routing sources to find out how to pass parameters to RouteUrl

**Comment by dougbu** [comment]
Please clarify why extension methods such as [this](https://github.com/pushist1y/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/UrlHelperExtensions.cs#L313-L319) are difficult to use.

**Comment by pushist1y** [comment]
@dougbu 
Firstly i'd like to clarify that it's not new approach, it's additional parameter to existing helper method `Action()` which previously was always considered `null`.

Secondly, the RouteUrl requires using of `RouteValueDictionary` which is essentially a `Dictionary<string, object>` which you have to populate with `{{"controller", "controllername"}, {"action", "actionname"}}` to work. And that process it neither obvious nor well documented. The best documentation I could find were comments in the Routing sources (exceptionally detailed though). 

Using 'Action()' method is much more obvious and possibility to specify route name is pretty useful if you have multiple named routes or mix of named and unnamed (attribute) routes.

**Comment by dougbu** [comment]
A named route should automatically be unique, making `controller` and `action` values irrelevant. 

Am I correct that you're trying to merge `Action()` and `RouteUrl()`? Seems the distinction between them is clear as-is but I may be missing something. In what scenarios would one person write the actions and their associated attributes and another write the `Action()` / `RouteUrl()` calls?

**Comment by pushist1y** [comment]
Personally i've run in this issue having a "default" route and two controllers with the same name one of which was intended to be called by the "default" route and another - by the attribute route (the "api" one). Building the website menu i've found that UrlHelper. `Action()` method could not distinguish controller names in and kept using that unnamed attribute route which essentialy pointed me to the wrong controller and i had no option to override that behaviour.

You can tell that I've found the workaroud via RouteUrl. But i've noticed a way to make `Action()` call more versatile and offered this PR. I strongly believe that there could me more usecases for that, especially if you have more global routes defined in the `AddMvc()` section.

**Comment by davidfowl** [comment]
This does seem strange when there's a RouteUrl letting you pass in the route name directly. Can you show some samples where it simplifies things? This change just seems like it's smashing 2 different things together.

**Comment by pushist1y** [comment]
I can't expose the whole repository, but i've added relevant files [here](https://github.com/pushist1y/ErrorReproductions/tree/master/UrlHelperAction).

The main points of reproduction:
1) Two controllers with same name (different namespaces)
2) "default" route declared in `Startup.cs`
3) unnamed "api" route declared as an attribute for api controller

You can see the most relevant part [here](https://gist.github.com/pushist1y/922eb8c4a98b384d048a95959a7a2a23)

**Comment by dougbu** [comment]
@pushist1y why doesn't [this `[Route]`](https://github.com/pushist1y/ErrorReproductions/blob/master/UrlHelperAction/Controllers/Api/UsersController.cs#L11) have a name?

**Comment by pushist1y** [comment]
@dougbu well, I didn't think it should. But it does not matter. The behaviour of `Action()` method does not change if I assign a name to this route.

**Comment by dougbu** [comment]
> The behaviour of `Action()` method does not change if I assign a name to this route.

That's by design. `Action()` _explicitly_ ignores the route name and focuses on `controller` and `action` values. By contrast, `RouteUrl()` requires a route name and does not use the ambient `controller` and `action` values. See [documentation](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing#generating-urls-by-route) for more information about how `RouteUrl()` intentionally differs from `Action()`.

Suggest reading the whole URL generation [section](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing#url-generation).

Back to this PR: Your scenario involves ambiguous controller names and requires named routes, areas, controller or action renames, or something more drastic to avoid URL generation issues. Having `Action()` sometimes behave like `RouteUrl()` (but copying `controller` and `action` values to the route values) creates new ambiguities and is more complex than other ways to fix your sample.

**Comment by pushist1y** [comment]
@dougbu looks like i've completely missed the whole Area concept. Thank you for your time anyway.

**Pull request closed without merging**
