### PR TITLE
Use stable locale when testing date/time formats

### PR DESCRIPTION
**Pull request by dougbu**
- `CultureReplacerMiddleware` no longer helping `RazorWebSite`
 - likely regressed with @30d11a8

### CODE REVIEW

**Comment by rynowak** [comment]
Isn't this change just going to fight with the localisation middleware? 

Would it be better to have functional tests that depend on locales play *with* the localization middleware and abandon `[ReplaceCulture]` for functional test? Not sure I'm convinced either way, but I wanted to pose the question.

**Comment by dougbu** [comment]
> Isn't this change just going to fight with the localisation middleware?

`RazorWebSite` configures both `CultureReplacerMiddleware` (our test middleware) and `RequestLocalizationMiddleware`. `RequestLocalizationMiddleware` is winning which means either the ambient culture must be given a consistent value (which is exactly what `[ReplaceCulture]` is for) or the test client would need to send an `Accept-Language` header (making it a different test). `CultureReplacerMiddleware` should probably be removed from this particular site since it is irrelevant.

**Comment by dougbu** [comment]
Updated per offline conversations...

**Comment by kirthik** [comment]
:shipit:

**Comment by dougbu** [comment]
cda2c67

**Pull request closed without merging**
