### PR TITLE
Removed custom object result accepting status code as out of box ObjectR...

### PR DESCRIPTION
**Pull request by kichalla**
...esult provides this already.

@ianhong @ajaybhargavb

### CODE REVIEW

**Comment by ianhong** [comment]
:shipit:

**Comment by rynowak** [comment]
@kichalla what was the corresponding test originally testing?

**Comment by kichalla** [comment]
@rynowak : This custom result was being used in the model validation filter to return back a 400 bad request with error info. There are 2 tests which verify for the status code 400 and the model state errors.

https://github.com/aspnet/Mvc/blob/00b61ec1e6f10e05fe0a83f0b42f71c714905ef1/test/Microsoft.AspNet.Mvc.FunctionalTests/InputObjectValidationTests.cs#L147

https://github.com/aspnet/Mvc/blob/00b61ec1e6f10e05fe0a83f0b42f71c714905ef1/test/Microsoft.AspNet.Mvc.FunctionalTests/InputObjectValidationTests.cs#L117

**Comment by rynowak** [comment]
:+1:

**Pull request merged**
