### PR TITLE
Added Conflict result helper to ControllerBase

### PR DESCRIPTION
**Pull request by mistakenot**
- Added ConflictObjectResult and ConflictResult types.
- Conflict(), Conflict(object error), Conflict(ModelState modelState)
added to ControllerBase.cs.
- Tests added to ControllerBaseTest.cs.
- Added ConflictObjectResultTest.cs and ConflictResultTest.cs.
- Fixed spelling in BadRequestObjectResultTests.cs

Addresses #6172

### CODE REVIEW

**Comment by rynowak** [comment]
@pranavkm can you take a look?

**Comment by pranavkm** [comment]
Thanks for the PR @mistakenot. Unfortunately I messed up the rebase and didn't realize until after I pushed - so it credits @rynowak for the change. Let me know if you feel strongly about this and we can do a identical merge commit attributing you for the change.

**Comment by pranavkm** [comment]
Merged in https://github.com/aspnet/Mvc/commit/e3ce1f52d4b5955e258e17b18ddc39d4b436268d

**Comment by mistakenot** [comment]
@pranavkm Would be quite nice to have my name on my first feature contribution, but don't break a sweat over it if it is a hassle :)

**Comment by pranavkm** [comment]
@mistakenot - done https://github.com/aspnet/Mvc/commit/c5f89a8b573a8001d9eaf65ec1626a4905ce23f8

**Pull request closed without merging**
