### PR TITLE
 * Linux FS is case sensitive

### PR DESCRIPTION
**Pull request by ryanbrandenburg**

### CODE REVIEW

**Comment by dougbu** [comment]
:shipit:

**Comment by muratg** [comment]
How did this work in our CI?

**Comment by ryanbrandenburg** [comment]
My guess is that the casing was the real problem here, so since aspnetCI is windows (case insensitive) vs the failing builds on Travis/linux (case sensitive) it didn't have any trouble with the path.

**Comment by ryanbrandenburg** [comment]
Looks like this fixes the problems we were having but there's something else that was hiding under it.

**Comment by ryanbrandenburg** [comment]
I'm just going to check this in and make the other fix as it's own PR since it improves things at least.

**Pull request merged**
