### PR TITLE
Use Hosting.Interfaces

### PR DESCRIPTION
**Pull request by rynowak**
/cc @davidfowl 

Kiran is working on removing the dependency on logging, but for now we still use it. We were getting it through the reference to Hosting before.

### CODE REVIEW

**Comment by davidfowl** [comment]
Logging.Interfaces

**Comment by rynowak** [comment]
> Logging.Interfaces

> Kiran is working on removing the dependency on logging, but for now we still use it. We were getting it through the reference to Hosting before.

L2ReadBro

**Comment by davidfowl** [comment]
Until then :smile:

**Comment by rynowak** [comment]
Any other useful feedback? All the logging stuff we did earlier depends on classes in `.Logging`, and it's already in progress being redone.

**Comment by davidfowl** [comment]
I dont think you depend on logging you only depend on interfaces (in Core)

**Comment by rynowak** [comment]
https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Framework.Logging/ReflectionBasedLogValues.cs
https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Framework.Logging/LoggerFactory.cs

**Comment by davidfowl** [comment]
MVC uses LoggerFactory in Core? Something is terribly wrong there.

**Comment by davidfowl** [comment]
Anyways :shipit:

**Comment by rynowak** [comment]
> MVC uses LoggerFactory in Core? Something is terribly wrong there.

Yep. I just found that. It's being used to log something that we're going to remove as part of logging cleanup so that will go away too.

**Pull request closed without merging**
