### PR TITLE
Update Mvc.Core and dependencies to netstandard1.6

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @ajaybhargavb \ @NTaylorMullen

**Comment by javiercn** [comment]
Don't we need to also update test projects?

**Comment by pranavkm** [comment]
@javiercn no, test projects target netcoreapp1.0 which is a super set.

**Comment by NTaylorMullen** [comment]
:shipit:

**Comment by ajaybhargavb** [comment]
:shipit:

**Comment by javiercn** [comment]
I thought it was the oposite, 1.0 had less stuff than 1.1 and so on, isn't that the case? If I'm wrong just :shipit:

**Comment by pranavkm** [comment]
I think netcoreapp1.0 targets netstandard1.6 (althought @davidfowl's sample says otherwise: https://github.com/davidfowl/NetStandard/blob/master/platforms.cs#L120)

**Comment by NTaylorMullen** [comment]
> I think netcoreapp1.0 targets netstandard1.6 (althought @davidfowl's sample says otherwise: https://github.com/davidfowl/NetStandard/blob/master/platforms.cs#L120)

Didn't david create that before netstandard1.6 was a thing?

**Comment by NTaylorMullen** [comment]
a

**Comment by NTaylorMullen** [comment]
s

**Pull request closed without merging**
