### PR TITLE
#2295 - Disposing the read stream after computing file hash.

### PR DESCRIPTION
**Pull request by sornaks**

### CODE REVIEW

**Comment by NTaylorMullen** [comment]
:shipit:

**Comment by Eilon** [comment]
:shipit: please check into release then port to dev.

**Comment by pranavkm** [comment]
@sornaks, this is checked in, isn't it?

**Comment by sornaks** [comment]
Yes. I forgot to close sorry. https://github.com/aspnet/Mvc/commit/6e9533ce9cf48536c27a09bf61fd48b113c2107b

**Pull request closed without merging**
