### PR TITLE
Using new IMetadataReference extension methods

### PR DESCRIPTION
**Pull request by pranavkm**
cc @rynowak  \ @davidfowl

### CODE REVIEW

**Comment by rynowak** [comment]
:shipit:

**Comment by davidfowl** [comment]
The ci is failing

**Comment by davidfowl** [comment]
You should cache based on the path. Write a test where you have N project references and see if you get the same metadata reference. I'm betting you won't

**Comment by pranavkm** [comment]
@davidfowl, I am caching on the path - https://github.com/aspnet/Mvc/pull/3078/files#diff-8fe1e17d71f328d3f4fbff84450b9f51R30

**Comment by davidfowl** [comment]
AppVeyor + Travis are failing here.

**Comment by pranavkm** [comment]
It's already been checked in.

**Pull request closed without merging**
