### PR TITLE
Revert DependencyModel version

### PR DESCRIPTION
**Pull request by JunTaoLuo**
https://github.com/aspnet/Mvc-Private/pull/8#issuecomment-344485491 but in the public repo.

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
FYI Coherence-Patch was updated to point to public repos: https://github.com/aspnet/Coherence-Patch/commit/b3708a3d2ee6306936e95398cdf705116d440943. 

Note, I specifically chose not to mark the HttpSysServer packages as "ship" in the packages.csv. However, I will manually copy over the two packages that were built previously for building the LZMA as I would like to use the same packages that were uploaded to nuget.

**Comment by natemcmaster** [comment]
Why are you requesting to merge from rel/1.1.6 to rel/1.1.5? Seems like this should stay in the rel/1.1.6 branch.

**Comment by pranavkm** [comment]
Could we branch to rel/1.1.6 and then send a PR to it?

**Comment by JunTaoLuo** [comment]
From the original PR:
> FYI. Diff with 1.1.5 for comparison but it's checked in as rel/1.1.6 which is what Coherence-Patch builds

I made the branch already as I wanted to be able to launch a build right away. This change isn't meant to be merged, it's meant to be a diff only.

**Comment by JunTaoLuo** [comment]
Already building with this branch. Note, do not delete this branch.

**Pull request closed without merging**
